### ISSUE TITLE
Small bugs in 1D_to_3D_projection.py?

### ISSUE THREAD

**Issue by JonathanPham** [suhaasa/Suhaas-useful-scripts#1]
Hey Suhaas,

I tried running your 1D_to_3D_projection.py and I got a couple of small errors. If I make the following changes (see below), then the code runs for me. Did you manage to run this code without making the changes below?

# 1D_to_3D_projection.py
1. Line 430: 'GlobalNodeID' changed to 'GlobalNodeId'
2. Lines 524 - 528:   
    f = open("file.pkl","wb")
    pickle.dump(graph.node_properties,f)
    props = pickle.load(f)
    mesh = addPropertiesFromDict(mesh,props)
    f.close()

    changed to:

    f = open("file.pkl","wb")
    pickle.dump(graph.node_properties,f)
    f.close()
    f = open("file.pkl","rb")
    props = pickle.load(f)
    mesh = addPropertiesFromDict(mesh,props)
    f.close()

**Comment by suhaasa** [comment]
thanks for letting me know!
